local shell = require("shell")

shell.setAlias("dir", "ls")
shell.setAlias("list", "ls")
shell.setAlias("move", "mv")
shell.setAlias("rename", "mv")
shell.setAlias("copy", "cp")
shell.setAlias("del", "rm")
shell.setAlias("md", "mkdir")
shell.setAlias("cls", "clear")
shell.setAlias("less", "more")
shell.setAlias("rs", "redstone")
shell.setAlias("view", "edit -r")
shell.setAlias("help", "man")
shell.setAlias("?", "man")
shell.setAlias("cp", "cp -i")
shell.setAlias("/bin/usage.lua", "usage")
sjell.setAlias("df", "usage")
shell.setAlias("logout", "/bin/logout.lua")
shell.setAlias("update", "/bin/update.lua")
shell.setAlias("adduser", "/bin/adduser.lua")
shell.setAlias("/bin/deluser.lua", "deluser")
shell.setAlias("rmuser", "deluser")
shell.setAlias("passwd", "/bin/passwd.lua")
shell.setAlias("reboot", "shutdown -r")
shell.setAlias("sudo", "/root/sudo.lua")

require("event").listen("init", function()
  local file = io.open("/etc/hostname")
  if file then
    os.setenv("HOSTNAME", file:read("*l"))
    os.setenv("PS1", "$HOSTNAME:$PWD# ")
    file:close()
  end
end)
